added exception handling for inputs

diff --git a/src/decrypt b/src/decrypt
--- a/src/decrypt
+++ b/src/decrypt
@@ -6,5 +6,19 @@
 file="$1"
 plain=${file%.enc}
 
+# ensure that input is not empty
+if [ -z "$file" ]; then
+  echo "decrypt: missing input"
+  exit 1
+fi
+
+# ensure that no existing file is overwritten
+if [ -f "./$plain" ]; then
+  echo "decrypt: cannot create ‘$plain’ - file exists"
+  exit 1
+fi
+
+echo "enter password:"
+
 openssl enc -in $file -d -aes-256-cbc -pass stdin > $plain
 rm $file
diff --git a/src/encrypt b/src/encrypt
--- a/src/encrypt
+++ b/src/encrypt
@@ -5,6 +5,19 @@
 
 file="$1"
 
+# ensure that input is not empty
+if [ -z "$file" ]; then
+  echo "encrypt: missing input"
+  exit 1
+fi
+
+# ensure that no existing file is overwritten
+if [ -f "./$file.enc" ]; then
+  echo "encrypt: cannot create ‘$file.enc’ - file exists"
+  exit 1
+fi
+
+echo "enter password and make sure to remember it:"
+
 openssl enc -in $file -aes-256-cbc -pass stdin > $file.enc
-echo "make sure you remember your password"
 rm $file
